version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./frontend/static:/app/frontend/static
      - ./backend/app:/app/backend/app
    environment:
      - PYTHONPATH=/app
    restart: unless-stopped